In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/AQI.csv")

In [2]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",19-05-2025 10:00:00,16.554731,80.649110,SO2,20.0,23.0,21.0
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",19-05-2025 10:00:00,16.554731,80.649110,OZONE,17.0,35.0,22.0
2,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",19-05-2025 10:00:00,17.720000,83.300000,PM10,23.0,66.0,36.0
3,India,Arunachal_Pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",19-05-2025 10:00:00,27.103358,93.679645,NO2,4.0,5.0,5.0
4,India,Arunachal_Pradesh,Naharlagun,"Naharlagun, Naharlagun - APSPCB",19-05-2025 10:00:00,27.103358,93.679645,CO,10.0,19.0,12.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3077 entries, 0 to 3076
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        3077 non-null   str
 1   state          3077 non-null   str
 2   city           3077 non-null   str
 3   station        3077 non-null   str
 4   last_update    3077 non-null   str
 5   latitude       3077 non-null   float64
 6   longitude      3077 non-null   float64
 7   pollutant_id   3077 non-null   str
 8   pollutant_min  2778 non-null   float64
 9   pollutant_max  2778 non-null   float64
 10  pollutant_avg  2778 non-null   float64
dtypes: float64(5), str(6)
memory usage: 264.6 KB

In [4]:
df.describe()

          latitude    longitude  pollutant_min  pollutant_max  pollutant_avg
count  3077.000000  3077.000000    2778.000000    2778.000000    2778.000000
mean     22.250067    78.682006      21.670986      59.251620      33.933765
std       5.519664     4.854371      25.535470      65.896529      36.125555
min       8.514909    70.909168       1.000000       1.000000       1.000000
25%      19.036458    75.521300       5.000000      15.000000       9.000000
50%      23.023389    77.508730      13.000000      40.000000      23.000000
75%      26.833997    80.723178      29.000000      79.000000      45.000000
max      34.066206    94.636574     303.000000     500.000000     336.000000

In [5]:
df.columns

Index(['country', 'state', 'city', 'station', 'last_update', 'latitude',
       'longitude', 'pollutant_id', 'pollutant_min', 'pollutant_max',
       'pollutant_avg'],
      dtype='str')

In [6]:
df.isnull().sum()

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    299
pollutant_max    299
pollutant_avg    299
dtype: int64