In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/AQI.csv")


print(df.head())

  StationId             Datetime  PM2.5    PM10    NO    NO2    NOx    NH3  \
0     AP001  2017-11-24 17:00:00  60.50   98.00  2.35  30.80  18.25   8.50
1     AP001  2017-11-24 18:00:00  65.50  111.25  2.70  24.20  15.07   9.77
2     AP001  2017-11-24 19:00:00  80.00  132.00  2.10  25.18  15.15  12.02
3     AP001  2017-11-24 20:00:00  81.50  133.25  1.95  16.25  10.23  11.58
4     AP001  2017-11-24 21:00:00  75.25  116.00  1.43  17.48  10.43  12.03

    CO    SO2      O3  Benzene  Toluene  Xylene  AQI AQI_Bucket
0  0.1  11.85  126.40      0.1     6.10    0.10  NaN        NaN
1  0.1  13.17  117.12      0.1     6.25    0.15  NaN        NaN
2  0.1  12.08   98.98      0.2     5.98    0.18  NaN        NaN
3  0.1  10.47  112.20      0.2     6.72    0.10  NaN        NaN
4  0.1   9.12  106.35      0.2     5.75    0.08  NaN        NaN

C:\Users\Sarosh\AppData\Local\Temp\ipykernel_25328\3339799981.py:3: DtypeWarning: Columns (0: AQI_Bucket) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/AQI.csv")

In [5]:
print(df["StationId"].nunique())

110

In [6]:
print(sorted(df["StationId"].unique()))

['AP001', 'AP005', 'AS001', 'BR005', 'BR006', 'BR007', 'BR008', 'BR009', 'BR010', 'CH001', 'DL001', 'DL002', 'DL003', 'DL004', 'DL005', 'DL006', 'DL007', 'DL008', 'DL009', 'DL010', 'DL011', 'DL012', 'DL013', 'DL014', 'DL015', 'DL016', 'DL017', 'DL018', 'DL019', 'DL020', 'DL021', 'DL022', 'DL023', 'DL024', 'DL025', 'DL026', 'DL027', 'DL028', 'DL029', 'DL030', 'DL031', 'DL032', 'DL033', 'DL034', 'DL035', 'DL036', 'DL037', 'DL038', 'GJ001', 'HR011', 'HR012', 'HR013', 'HR014', 'JH001', 'KA002', 'KA003', 'KA004', 'KA005', 'KA006', 'KA007', 'KA008', 'KA009', 'KA010', 'KA011', 'KL002', 'KL004', 'KL007', 'KL008', 'MH005', 'MH006', 'MH007', 'MH008', 'MH009', 'MH010', 'MH011', 'MH012', 'MH013', 'MH014', 'ML001', 'MP001', 'MZ001', 'OD001', 'OD002', 'PB001', 'RJ004', 'RJ005', 'RJ006', 'TG001', 'TG002', 'TG003', 'TG004', 'TG005', 'TG006', 'TN001', 'TN002', 'TN003', 'TN004', 'TN005', 'UP012', 'UP013', 'UP014', 'UP015', 'UP016', 'WB007', 'WB008', 'WB009', 'WB010', 'WB011', 'WB012', 'WB013']

In [7]:
station_counts = (
    df.groupby("StationId")["AQI"]
      .count()
      .sort_values(ascending=False)
)

print(station_counts)

StationId
DL031    39207
UP012    39176
UP014    38890
TN001    38698
KA009    36580
         ...
HR013     2705
MZ001     2528
BR006     2437
BR005     1689
DL011        0
Name: AQI, Length: 110, dtype: int64

In [8]:
delhi_df = df[df["StationId"].str.startswith("DL")].copy()

print(delhi_df.shape)

(1087388, 16)

In [9]:
print(delhi_df["AQI"].isnull().sum())
print(delhi_df["AQI"].notnull().sum())

241288
846100

In [10]:
delhi_df = delhi_df.dropna(subset=["AQI"])

print(delhi_df.shape)

(846100, 16)

In [12]:
delhi_df["Datetime"] = pd.to_datetime(delhi_df["Datetime"])
delhi_df = delhi_df.sort_values("Datetime")

In [13]:
delhi_df.to_csv("../data/processed/delhi_bootstrap.csv", index=False)

Bootstrap Dataset

In [15]:
import pandas as pd

df = pd.read_csv("../data/raw/AQI.csv")

C:\Users\Sarosh\AppData\Local\Temp\ipykernel_25328\888681790.py:3: DtypeWarning: Columns (0: AQI_Bucket) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/AQI.csv")

In [16]:
delhi_df = df[df["StationId"].str.startswith("DL")].copy()

print(delhi_df.shape)

(1087388, 16)

In [17]:
delhi_df = delhi_df.dropna(subset=["AQI"])

print(delhi_df.shape)

(846100, 16)

In [18]:
delhi_df["Datetime"] = pd.to_datetime(delhi_df["Datetime"])

In [19]:
delhi_df = delhi_df.sort_values("Datetime")

In [20]:
bootstrap_df = (
    delhi_df
    .groupby("Datetime")
    .agg({
        "AQI": "median",
        "PM2.5": "median",
        "PM10": "median",
        "NO2": "median",
        "NO": "median",
        "NOx": "median",
        "NH3": "median",
        "CO": "median",
        "SO2": "median",
        "O3": "median"
    })
    .reset_index()
)

In [21]:
bootstrap_df.head()

,Datetime,AQI,PM2.5,PM10,NO2,NO,NOx,NH3,CO,SO2,O3
0,2015-01-01 16:00:00,456.5,211.510,340.66,30.210,14.805,43.905,38.34,10.975,14.0,110.16
1,2015-01-01 17:00:00,450.0,191.120,257.40,31.250,15.510,44.820,40.96,12.225,18.5,109.76
2,2015-01-01 18:00:00,446.5,218.440,351.01,30.825,18.270,47.145,40.84,13.445,24.5,123.91
3,2015-01-01 19:00:00,475.0,296.805,600.95,30.640,26.560,54.505,38.74,14.340,32.0,159.48
4,2015-01-01 20:00:00,480.0,336.430,714.63,29.655,31.295,57.805,41.50,8.845,22.5,173.27

In [22]:
bootstrap_df.isnull().sum()

Datetime       0
AQI            0
PM2.5        144
PM10        3119
NO2          126
NO           168
NOx          223
NH3         2152
CO          2739
SO2         2895
O3          1960
dtype: int64

In [23]:
bootstrap_df.to_csv(
    "../data/processed/delhi_bootstrap.csv",
    index=False
)

In [24]:
print(bootstrap_df["Datetime"].min())
print(bootstrap_df["Datetime"].max())

2015-01-01 16:00:00
2020-07-01 00:00:00

In [28]:
import pandas as pd

weather = pd.read_csv("../data/weather/delhi_weather.csv")

print(weather.head())

print(weather.shape)

print(weather.columns)

print(weather.isnull().sum())

              Datetime  tempC  humidity  precipMm  windSpeedKmh  windDirDeg
0  2015-01-01 00:00:00   12.5        81       0.0           7.6         360
1  2015-01-01 01:00:00   12.1        83       0.0           7.9         357
2  2015-01-01 02:00:00   11.8        84       0.0           7.9           3
3  2015-01-01 03:00:00   13.0        80       0.0           6.9           9
4  2015-01-01 04:00:00   15.6        69       0.0           3.9          22
(48216, 6)
Index(['Datetime', 'tempC', 'humidity', 'precipMm', 'windSpeedKmh',
       'windDirDeg'],
      dtype='str')
Datetime        0
tempC           0
humidity        0
precipMm        0
windSpeedKmh    0
windDirDeg      0
dtype: int64

In [29]:
bootstrap_df["Datetime"] = pd.to_datetime(bootstrap_df["Datetime"])
weather["Datetime"] = pd.to_datetime(weather["Datetime"])

In [30]:
merged_df = bootstrap_df.merge(
    weather,
    on="Datetime",
    how="inner"
)

print(merged_df.shape)
merged_df.head()

(47694, 16)

,Datetime,AQI,PM2.5,PM10,NO2,NO,NOx,NH3,CO,SO2,O3,tempC,humidity,precipMm,windSpeedKmh,windDirDeg
0,2015-01-01 16:00:00,456.5,211.510,340.66,30.210,14.805,43.905,38.34,10.975,14.0,110.16,15.8,73,0.0,6.3,167
1,2015-01-01 17:00:00,450.0,191.120,257.40,31.250,15.510,44.820,40.96,12.225,18.5,109.76,15.5,76,0.0,6.2,159
2,2015-01-01 18:00:00,446.5,218.440,351.01,30.825,18.270,47.145,40.84,13.445,24.5,123.91,14.8,80,0.0,5.3,152
3,2015-01-01 19:00:00,475.0,296.805,600.95,30.640,26.560,54.505,38.74,14.340,32.0,159.48,15.1,80,0.0,3.0,104
4,2015-01-01 20:00:00,480.0,336.430,714.63,29.655,31.295,57.805,41.50,8.845,22.5,173.27,14.7,83,0.0,2.3,72

In [31]:
merged_df.isnull().sum()

Datetime           0
AQI                0
PM2.5            144
PM10            3119
NO2              126
NO               168
NOx              223
NH3             2152
CO              2739
SO2             2895
O3              1960
tempC              0
humidity           0
precipMm           0
windSpeedKmh       0
windDirDeg         0
dtype: int64

In [32]:
merged_df.to_csv(
    "../data/processed/delhi_bootstrap_weather.csv",
    index=False
)

In [33]:
print(delhi_df["StationId"].value_counts())

StationId
DL031    39207
DL002    35979
DL021    35903
DL028    33885
DL019    31688
DL013    28795
DL007    27851
DL034    27323
DL033    24763
DL012    22864
DL004    22740
DL017    22074
DL030    21844
DL008    21335
DL025    21295
DL010    20942
DL024    20939
DL003    20902
DL018    20891
DL015    20832
DL014    20802
DL027    20765
DL026    20710
DL016    20685
DL032    20681
DL009    20674
DL038    20662
DL035    20542
DL037    20486
DL023    20238
DL022    20130
DL005    17195
DL036    17184
DL020    16910
DL006    16299
DL029    16263
DL001    13822
Name: count, dtype: int64

In [34]:
coverage = (
    df[df["StationId"].str.startswith("DL")]
      .groupby("StationId")
      .agg(
          total_rows=("AQI", "size"),
          valid_aqi=("AQI", lambda x: x.notna().sum())
      )
)

coverage["completeness"] = (
    coverage["valid_aqi"] / coverage["total_rows"]
)

coverage = coverage.sort_values(
    ["completeness", "valid_aqi"],
    ascending=False
)

print(coverage.head(10))

KeyError: 'StationId'

In [35]:
print(df.columns)

Index(['Datetime', 'tempC', 'humidity', 'precipMm', 'windSpeedKmh',
       'windDirDeg'],
      dtype='str')

In [36]:
import pandas as pd

raw_df = pd.read_csv("../data/raw/AQI.csv")

coverage = (
    raw_df[raw_df["StationId"].str.startswith("DL")]
    .groupby("StationId")
    .agg(
        total_rows=("AQI", "size"),
        valid_aqi=("AQI", lambda x: x.notna().sum())
    )
)

coverage["completeness"] = (
    coverage["valid_aqi"] / coverage["total_rows"]
)

coverage = coverage.sort_values(
    ["completeness", "valid_aqi"],
    ascending=False
)

print(coverage.head(10))

C:\Users\Sarosh\AppData\Local\Temp\ipykernel_25328\69504891.py:3: DtypeWarning: Columns (0: AQI_Bucket) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv("../data/raw/AQI.csv")

           total_rows  valid_aqi  completeness
StationId
DL010           21137      20942      0.990774
DL024           21134      20939      0.990773
DL003           21136      20902      0.988929
DL018           21144      20891      0.988034
DL015           21136      20832      0.985617
DL005           17454      17195      0.985161
DL036           17478      17184      0.983179
DL027           21134      20765      0.982540
DL026           21134      20710      0.979938
DL016           21136      20685      0.978662